# SPDX-License-Identifier: AGPL-3.0-or-later
"""The policy permutation lab: every user-tunable option, exercised over real shapes.

The policy engine exposes a large option surface -- gates with thresholds and windows,
weighted signals, user-authored condemn rules, protect conditions, graded keeps, two
decision thresholds, and eight season-pruning toggles. Any combination is a legal
operator configuration, and a bug in an untested combination deletes files. This module
sweeps that space against ``tests/fixtures/policy_lab_vectors.json``: a de-identified
sample of real library shapes (observation states, day counts, watcher counts) with a
pinned baseline, generated by ``scripts/policy_lab_extract.py``.

Every check here is an *invariant*, not an example: a property that must hold across the
whole permutation space, in the direction that keeps files. The three load-bearing ones:

* **Missing data never condemns.** Degrading any fact to Unknown may never flip an item
  into the condemned set, and may never raise its score.
* **Protections only ever narrow the condemned set.** Adding a gate, a protect
  condition, or a keep can never condemn something the same policy without it spared.
* **Anything that validates must score.** A policy the save boundary accepts must run
  through gates, scorer, and verdict without an exception, on every real shape.

The pinned baseline turns the fixture into an engine-drift trip-wire: any change to
scoring or verdict semantics shows up as a baseline diff, which an intentional change
acknowledges by regenerating the fixture.
"""

from __future__ import annotations

import itertools
import json
import random

import pytest
from hypothesis import given, settings
from hypothesis import strategies as st

from reaper.clients.sonarr_stats import SeasonStats
from reaper.engine.fields import BY_KEY, Lane, Op
from reaper.engine.gates import GateId
from reaper.engine.policy import (
    DEFAULT_MOVIE_POLICY,
    DEFAULT_TV_POLICY,
    PolicyBody,
    ProfileSettings,
    inspect,
)
from reaper.engine.signals import SignalId
from reaper.engine.verdict import decide_verdict
from reaper.services.scan_runner import build_gates
from reaper.services.season_pruning import active_progress, plan_series_prune
from tests._policy_lab import (
    DEGRADABLE,
    FIXTURE,
    VERDICT_RANK,
    degraded,
    judge,
    load_fixture,
    with_watchers_window,
)

FIX = load_fixture()
VECTORS = FIX["vectors"]
MOVIES = [v for v in VECTORS if v["media_type"] == "movie"]
SEASONS = [v for v in VECTORS if v["media_type"] == "season"]
SHOWS = FIX["shows"]

MOVIE_GATES = build_gates(DEFAULT_MOVIE_POLICY)
TV_GATES = build_gates(DEFAULT_TV_POLICY)


def default_policy(media_type: str) -> PolicyBody:
    return DEFAULT_MOVIE_POLICY if media_type == "movie" else DEFAULT_TV_POLICY


def default_gates(media_type: str) -> list:
    return MOVIE_GATES if media_type == "movie" else TV_GATES


def mutated(policy: PolicyBody, **changes) -> PolicyBody:
    """A policy with fields replaced, re-validated -- never a validation bypass.

    ``model_copy(update=...)`` skips validators, which would let a test exercise a policy
    no operator can save. Round-trip through ``model_validate`` so every policy judged
    here is one the API would accept.
    """
    body = policy.model_dump(mode="json")
    body.update(dict(changes.items()))
    return PolicyBody.model_validate(body)


def balanced(signals: list[dict]) -> list[dict]:
    """Drawn weights rescaled to total exactly 100, keeping their relative shape.

    The generators below draw each weight independently, which no longer validates: the
    budget rule requires the total to be exactly ``MAX_SCORE``. Rescaling rather than
    re-drawing keeps the property tests sweeping the same *shape* of policy (one dominant
    signal, four even ones, a signal switched off) instead of narrowing them to whatever
    happens to sum to 100 by luck.

    Largest-remainder allocation, so the parts sum exactly and no weight is lost to
    rounding. A signal drawn at 0 stays 0: switching one off is a real policy, and the
    sweep should keep covering it.
    """
    total = sum(s["weight"] for s in signals)
    if total == 0:
        signals[0]["weight"] = 100
        return signals
    exact = [s["weight"] * 100 / total for s in signals]
    floors = [int(x) for x in exact]
    remainder = 100 - sum(floors)
    # Hand the leftover points to the largest fractional parts, biggest first.
    order = sorted(range(len(signals)), key=lambda i: exact[i] - floors[i], reverse=True)
    for i in order[:remainder]:
        floors[i] += 1
    for s, w in zip(signals, floors, strict=True):
        s["weight"] = w
    return signals


def with_rule(policy: PolicyBody, rule: dict) -> PolicyBody:
    """``policy`` plus one custom rule, funded from the heaviest built-in signal.

    Removal weights total exactly 100 (``PolicyBody._weights_total_one_hundred``), so a
    rule cannot be bolted on: its points have to come from somewhere. This is the same
    trade the policy editor makes an operator make by hand, so tests that add a rule go
    through it rather than round a policy no operator could save.
    """
    body = policy.model_dump(mode="json")
    cost = int(rule.get("weight") or 0)
    if cost:
        funder = max(body["signals"], key=lambda s: s["weight"])
        if funder["weight"] < cost:
            raise AssertionError(
                f"no built-in signal can fund a rule of {cost}; heaviest is {funder['weight']}"
            )
        funder["weight"] -= cost
    body["custom_condemn"] = [rule]
    return PolicyBody.model_validate(body)


# ---------------------------------------------------------------------------
# The pinned baseline: engine drift shows up as a diff here
# ---------------------------------------------------------------------------


class TestPinnedBaseline:
    def test_every_vector_reproduces_its_baseline_under_the_default_policies(self) -> None:
        """If this fails, the engine's behaviour changed for real library shapes.

        That may be intentional -- a scorer change bumps SCORER_VERSION -- in which case
        regenerate the fixture (scripts/policy_lab_extract.py) in the same change, so the
        diff records exactly what moved. If you did not mean to change scoring, this is
        the bug.
        """
        mismatches = []
        for v in VECTORS:
            verdict, score, coverage_bp, _, _ = judge(
                v, default_policy(v["media_type"]), default_gates(v["media_type"])
            )
            base = v["baseline"]
            if (verdict, score, coverage_bp) != (
                base["verdict"],
                base["score"],
                base["coverage_bp"],
            ):
                mismatches.append(
                    f"{v['id']}: baseline {base} -> ({verdict}, {score}, {coverage_bp})"
                )
        assert not mismatches, "\n".join(mismatches[:10])


class TestFixtureStaysDeidentified:
    def test_no_identifying_fields_survive_regeneration(self) -> None:
        """The fixture is committed; the golden rule applies to it as to code. Guard the
        regeneration script against ever re-leaking titles, keys, paths, or hosts."""
        raw = FIXTURE.read_text()
        data = json.loads(raw)
        forbidden = {"title", "media_key", "group_key", "rating_key", "host", "path", "user"}

        def walk(obj) -> None:
            if isinstance(obj, dict):
                for key, value in obj.items():
                    assert key not in forbidden, f"identifying key {key!r} in fixture"
                    walk(value)
            elif isinstance(obj, list):
                for value in obj:
                    walk(value)

        walk(data)
        for v in data["vectors"]:
            genres = v["facts"]["genres"]
            if genres["state"] == "known":
                for token in genres["value"].split(", "):
                    assert token.startswith("Genre"), f"raw genre name {token!r} in fixture"


# ---------------------------------------------------------------------------
# Thresholds and gates: every knob moves the condemned set one way only
# ---------------------------------------------------------------------------


class TestThresholdMonotonicity:
    @pytest.mark.parametrize("media_type", ["movie", "season"])
    def test_raising_either_threshold_never_grows_the_condemned_set(self, media_type: str) -> None:
        pool = MOVIES if media_type == "movie" else SEASONS
        policy = default_policy(media_type)
        judged = [(v, judge(v, policy, default_gates(media_type))) for v in pool]
        grid = {}
        for condemn_at in (1, 30, 69, 70, 71, 100):
            for floor_bp in (0, 2500, 5000, 10000):
                condemned = set()
                for v, (_, score, coverage_bp, evaluation, _) in judged:
                    verdict = decide_verdict(
                        protected=evaluation.protected,
                        blocked=evaluation.blocked,
                        safety_protected=False,
                        score=score,
                        coverage_bp=coverage_bp,
                        condemn_at=condemn_at,
                        coverage_floor_bp=floor_bp,
                        override=v.get("override"),
                    )
                    if verdict == "condemn":
                        condemned.add(v["id"])
                grid[(condemn_at, floor_bp)] = condemned
        for floor_bp in (0, 2500, 5000, 10000):
            for low, high in itertools.pairwise((1, 30, 69, 70, 71, 100)):
                assert grid[(high, floor_bp)] <= grid[(low, floor_bp)]
        for condemn_at in (1, 30, 69, 70, 71, 100):
            for low, high in itertools.pairwise((0, 2500, 5000, 10000)):
                assert grid[(condemn_at, high)] <= grid[(condemn_at, low)]


class TestGateToggles:
    @pytest.mark.parametrize("media_type", ["movie", "season"])
    def test_dropping_any_gate_only_moves_verdicts_toward_condemn(self, media_type: str) -> None:
        """Removing a protection may condemn more, never less -- and never un-condemn."""
        pool = (MOVIES if media_type == "movie" else SEASONS)[:120]
        policy = default_policy(media_type)
        baseline = {v["id"]: judge(v, policy, default_gates(media_type))[0] for v in pool}
        for dropped in [g.gate for g in policy.gates]:
            without = mutated(
                policy,
                gates=[g.model_dump(mode="json") for g in policy.gates if g.gate is not dropped],
            )
            gates = build_gates(without)
            for v in pool:
                after = judge(v, without, gates)[0]
                assert VERDICT_RANK[after] >= VERDICT_RANK[baseline[v["id"]]], (
                    f"dropping {dropped.value} moved {v['id']} toward protection"
                )

    @pytest.mark.parametrize("media_type", ["movie", "season"])
    def test_random_gate_subsets_hold_the_same_direction(self, media_type: str) -> None:
        rng = random.Random(1)
        pool = (MOVIES if media_type == "movie" else SEASONS)[:80]
        policy = default_policy(media_type)
        baseline = {v["id"]: judge(v, policy, default_gates(media_type))[0] for v in pool}
        for _ in range(8):
            subset = [g for g in policy.gates if rng.random() > 0.4]
            smaller = mutated(policy, gates=[g.model_dump(mode="json") for g in subset])
            gates = build_gates(smaller)
            for v in pool:
                after = judge(v, smaller, gates)[0]
                assert VERDICT_RANK[after] >= VERDICT_RANK[baseline[v["id"]]]


class TestGateThresholds:
    def test_a_higher_rating_floor_never_protects_more(self) -> None:
        # The rating floor now lives in keep_rating_rules (one IMDb bar), so raise the bar
        # there and confirm the protected set only ever shrinks.
        protected_at: dict[int, set[str]] = {}
        for floor in (1, 50, 75, 90, 100):
            policy = mutated(
                DEFAULT_MOVIE_POLICY,
                keep_rating_rules=[{"source": "imdb", "floor": floor, "min_votes": 1000}],
            )
            gates = build_gates(policy)
            protected_at[floor] = {
                v["id"] for v in MOVIES if judge(v, policy, gates)[0] == "protect"
            }
        for low, high in itertools.pairwise((1, 50, 75, 90, 100)):
            assert protected_at[high] <= protected_at[low]

    def test_a_longer_dormancy_floor_never_protects_less(self) -> None:
        protected_at: dict[int, set[str]] = {}
        for threshold in (365, 730, 1095, 3650):
            policy = mutated(
                DEFAULT_MOVIE_POLICY,
                gates=[
                    {**g.model_dump(mode="json"), "threshold": threshold}
                    if g.gate is GateId.MIN_DORMANCY
                    else g.model_dump(mode="json")
                    for g in DEFAULT_MOVIE_POLICY.gates
                ],
            )
            gates = build_gates(policy)
            protected_at[threshold] = {
                v["id"] for v in MOVIES if judge(v, policy, gates)[0] == "protect"
            }
        for low, high in itertools.pairwise((365, 730, 1095, 3650)):
            assert protected_at[low] <= protected_at[high]

    def test_a_wider_popularity_window_never_protects_less(self) -> None:
        """Watchers are recomputed per window from the fixture's real play recency, the
        way a real scan would gather them -- not merely re-thresholded."""
        protected_at: dict[int, set[str]] = {}
        for window in (7, 90, 365, 1825):
            policy = mutated(
                DEFAULT_MOVIE_POLICY,
                gates=[
                    {**g.model_dump(mode="json"), "window_days": window}
                    if g.gate is GateId.SERVER_POPULARITY
                    else g.model_dump(mode="json")
                    for g in DEFAULT_MOVIE_POLICY.gates
                ],
            )
            gates = build_gates(policy)
            protected_at[window] = {
                v["id"]
                for v in MOVIES
                if judge(with_watchers_window(v, window), policy, gates)[0] == "protect"
            }
        for low, high in itertools.pairwise((7, 90, 365, 1825)):
            assert protected_at[low] <= protected_at[high]


# ---------------------------------------------------------------------------
# The user-authored surface: conditions, rules, keeps -- every field and operator
# ---------------------------------------------------------------------------

TEXT_VALUES = {
    "genre": ["Genre01", "genre01 , Genre02", "NoSuchGenre"],
    "quality": ["Bluray-1080p", "1080", "NoSuchQuality"],
    "on_curated_list": ["ListA", "NoSuchList"],
}
NUMERIC_VALUES = {
    "days_unwatched": [0, 365, 100000],
    "size_bytes": [0, 20_000_000_000],
    "recent_watchers": [0, 3],
    "watchers_all_time": [0, 5],
    "imdb_rating": [40, 75],
    "imdb_votes": [1, 100000],
    "season_rank": [1, 6],
    "release_age": [365, 40000],
}


def values_for(key: str, op: Op) -> list:
    spec = BY_KEY[key]
    if key in NUMERIC_VALUES:
        pool: list = NUMERIC_VALUES[key]
    elif key in TEXT_VALUES:
        pool = TEXT_VALUES[key]
    elif spec.type.value == "bool":
        pool = [True, False]
    else:
        pool = ["x"]
    if op in (Op.IN, Op.CONTAINS):
        return [v for v in pool if isinstance(v, str)]
    return pool


class TestProtectConditions:
    @pytest.mark.parametrize("key", [s.key for s in BY_KEY.values() if Lane.PROTECT in s.lanes])
    def test_adding_a_protect_condition_never_moves_an_item_toward_condemn(self, key: str) -> None:
        spec = BY_KEY[key]
        for media_type in ("movie", "season"):
            pool = (MOVIES if media_type == "movie" else SEASONS)[:60]
            policy = default_policy(media_type)
            baseline = {v["id"]: judge(v, policy, default_gates(media_type))[0] for v in pool}
            for op in spec.ops:
                for value in values_for(key, op):
                    with_condition = mutated(
                        policy,
                        protect_conditions=[{"field": key, "op": op.value, "value": value}],
                    )
                    gates = build_gates(with_condition)
                    for v in pool:
                        after = judge(v, with_condition, gates)[0]
                        assert VERDICT_RANK[after] <= VERDICT_RANK[baseline[v["id"]]], (
                            f"protect {key} {op.value} {value!r} moved {v['id']} "
                            f"{baseline[v['id']]} -> {after}"
                        )


class TestCustomCondemnRules:
    @pytest.mark.parametrize("key", [s.key for s in BY_KEY.values() if Lane.CONDEMN in s.lanes])
    def test_every_boolean_rule_scores_in_bounds_and_weight_zero_is_a_no_op(self, key: str) -> None:
        spec = BY_KEY[key]
        for media_type in ("movie", "season"):
            pool = (MOVIES if media_type == "movie" else SEASONS)[:60]
            policy = default_policy(media_type)
            baseline = {v["id"]: judge(v, policy, default_gates(media_type))[:3] for v in pool}
            for op in spec.ops:
                for value in values_for(key, op):
                    rule = {
                        "kind": "boolean",
                        "name": "rule-under-test",
                        "field": key,
                        "op": op.value,
                        "value": value,
                        "weight": 50,
                    }
                    armed = with_rule(policy, rule)
                    gates = build_gates(armed)
                    for v in pool:
                        _verdict, score, coverage_bp, _, _ = judge(v, armed, gates)
                        assert 0 <= score <= 100
                        assert 0 <= coverage_bp <= 10000
                    disarmed = with_rule(policy, {**rule, "weight": 0})
                    gates0 = build_gates(disarmed)
                    for v in pool[:20]:
                        assert judge(v, disarmed, gates0)[:3] == baseline[v["id"]], (
                            f"weight-0 rule on {key} changed an outcome"
                        )

    @pytest.mark.parametrize(
        "key",
        [
            s.key
            for s in BY_KEY.values()
            if Lane.CONDEMN in s.lanes and Op.GTE in s.ops and s.key in NUMERIC_VALUES
        ],
    )
    def test_every_graded_rule_scores_in_bounds_at_edge_ramps(self, key: str) -> None:
        for media_type in ("movie", "season"):
            pool = (MOVIES if media_type == "movie" else SEASONS)[:60]
            policy = default_policy(media_type)
            for floor, saturate in ((0, 1), (364, 365), (0, 10**9)):
                armed = with_rule(
                    policy,
                    {
                        "kind": "graded",
                        "name": "graded-under-test",
                        "field": key,
                        "weight": 60,
                        "floor": floor,
                        "saturate_at": saturate,
                    },
                )
                gates = build_gates(armed)
                for v in pool:
                    _verdict, score, coverage_bp, _, _ = judge(v, armed, gates)
                    assert 0 <= score <= 100
                    assert 0 <= coverage_bp <= 10000

    def test_a_rule_on_a_field_the_media_type_never_carries_does_not_sink_coverage(
        self,
    ) -> None:
        """Absent is evidence, not blindness: a graded rule on ``season_rank`` must not
        drag every MOVIE under the coverage floor (movies genuinely have no season)."""
        armed = with_rule(
            DEFAULT_MOVIE_POLICY,
            {
                "kind": "graded",
                "name": "rank-rule",
                "field": "season_rank",
                "weight": 40,
                "floor": 0,
                "saturate_at": 10,
            },
        )
        gates = build_gates(armed)
        for v in MOVIES[:60]:
            _, _, _coverage_bp, _, item_score = judge(v, armed, gates)
            rule = next(r for r in item_score.results if r.signal == "rank-rule")
            assert rule.evaluated, "Absent input must count as evaluated"
            assert rule.pressure == 0.0

    def test_a_custom_rule_may_not_shadow_a_builtin_signal_name(self) -> None:
        """Regression: the stored explanation identifies rows by this string; a rule
        named like a built-in would lose its "Your rule" tag and collide in the panel."""
        for name in (s.value for s in SignalId):
            with pytest.raises(ValueError, match="built-in signal"):
                with_rule(
                    DEFAULT_MOVIE_POLICY,
                    {
                        "kind": "boolean",
                        "name": name,
                        "field": "genre",
                        "op": "contains",
                        "value": "Genre01",
                        "weight": 10,
                    },
                )


class TestGradedKeeps:
    @pytest.mark.parametrize(
        "key", [s.key for s in BY_KEY.values() if Op.GTE in s.ops and s.key in NUMERIC_VALUES]
    )
    @pytest.mark.parametrize("direction", ["high_keeps", "low_keeps"])
    def test_a_keep_never_raises_a_score_and_never_moves_toward_condemn(
        self, key: str, direction: str
    ) -> None:
        for media_type in ("movie", "season"):
            pool = (MOVIES if media_type == "movie" else SEASONS)[:60]
            policy = default_policy(media_type)
            baseline = {v["id"]: judge(v, policy, default_gates(media_type))[:2] for v in pool}
            armed = mutated(
                policy,
                graded_keeps=[
                    {
                        "name": "keep-under-test",
                        "field": key,
                        "max_discount": 40,
                        "floor": 0,
                        "saturate_at": max(NUMERIC_VALUES[key]) or 1,
                        "direction": direction,
                    }
                ],
            )
            gates = build_gates(armed)
            for v in pool:
                verdict, score = judge(v, armed, gates)[:2]
                base_verdict, base_score = baseline[v["id"]]
                assert score <= base_score
                assert VERDICT_RANK[verdict] <= VERDICT_RANK[base_verdict]


# ---------------------------------------------------------------------------
# The core safety property: missing data never condemns
# ---------------------------------------------------------------------------


class TestUnknownDegradation:
    def _random_policy(self, rng: random.Random, media_type: str) -> PolicyBody:
        policy = default_policy(media_type)
        gates = []
        for g in policy.gates:
            entry = g.model_dump(mode="json")
            if g.gate is GateId.RATING_FLOOR:
                entry.update(threshold=rng.randint(1, 100), secondary=rng.randint(1, 10000))
            elif g.gate is GateId.MIN_DORMANCY:
                entry.update(threshold=rng.randint(365, 4000))
            elif g.gate is GateId.SERVER_POPULARITY:
                entry.update(threshold=rng.randint(1, 10), window_days=rng.randint(1, 2000))
            gates.append(entry)
        signals = [
            {**s.model_dump(mode="json"), "weight": rng.randint(0, 100)} for s in policy.signals
        ]
        signals = balanced(signals)
        return mutated(
            policy,
            gates=gates,
            signals=signals,
            condemn_at=rng.randint(1, 100),
            coverage_floor_bp=rng.choice((0, 2500, 5000, 8000)),
        )

    @pytest.mark.parametrize("media_type", ["movie", "season"])
    def test_degrading_any_fact_to_unknown_never_condemns_and_never_raises_a_score(
        self, media_type: str
    ) -> None:
        rng = random.Random(2)
        pool = (MOVIES if media_type == "movie" else SEASONS)[:70]
        policies = [default_policy(media_type)] + [
            self._random_policy(rng, media_type) for _ in range(5)
        ]
        for policy in policies:
            gates = build_gates(policy)
            for v in pool:
                verdict, score = judge(v, policy, gates)[:2]
                known = [n for n in DEGRADABLE if v["facts"][n]["state"] == "known"]
                probes = [[n] for n in known]
                if len(known) >= 3:
                    probes.append(rng.sample(known, 3))
                for names in probes:
                    after_verdict, after_score = judge(degraded(v, names), policy, gates)[:2]
                    assert after_score <= score, (
                        f"degrading {names} raised the score {score} -> {after_score}"
                    )
                    if verdict != "condemn":
                        assert after_verdict != "condemn", (
                            f"degrading {names} flipped {v['id']} {verdict} -> condemn"
                        )


# ---------------------------------------------------------------------------
# The single decision function, at every boundary
# ---------------------------------------------------------------------------


class TestDecideVerdictMatrix:
    def test_the_decision_matches_its_spec_at_every_boundary(self) -> None:
        for protected in (False, True):
            for blocked in (False, True):
                for safety in (False, True):
                    for override in (None, "reap"):
                        for score, condemn_at in ((69, 70), (70, 70), (0, 1), (100, 100)):
                            for coverage_bp, floor_bp in (
                                (4999, 5000),
                                (5000, 5000),
                                (0, 0),
                                (10000, 0),
                            ):
                                got = decide_verdict(
                                    protected=protected,
                                    blocked=blocked,
                                    safety_protected=safety,
                                    score=score,
                                    coverage_bp=coverage_bp,
                                    condemn_at=condemn_at,
                                    coverage_floor_bp=floor_bp,
                                    override=override,
                                )
                                if override == "reap":
                                    expect = "protect" if (blocked or safety) else "condemn"
                                elif protected:
                                    expect = "protect"
                                elif blocked or coverage_bp < floor_bp:
                                    expect = "abstain"
                                elif score >= condemn_at:
                                    expect = "condemn"
                                else:
                                    expect = "abstain"
                                assert got == expect


# ---------------------------------------------------------------------------
# Season pruning: eight toggles over real show shapes
# ---------------------------------------------------------------------------


def _season(number: int, *, files: int = 8, wanted: int = 0) -> SeasonStats:
    return SeasonStats(
        season_number=number,
        monitored=True,
        episode_file_count=files,
        size_on_disk=10,
        total_episode_count=max(files, 8),
        wanted_episode_count=wanted,
    )


class TestSeasonPlanPermutations:
    def test_every_option_combination_holds_the_plan_invariants_on_real_shapes(
        self,
    ) -> None:
        checked = 0
        for show in SHOWS:
            numbers = [n for n, _ in show["seasons"]]
            watchers = dict(show["seasons"])
            stats = [_season(n) for n in numbers]
            real = [n for n in numbers if n != 0]
            for keep_last, keep_first, keep_specials, flag in itertools.product(
                (0, 1, 2, 10), (True, False), (True, False), (True, False)
            ):
                plan = plan_series_prune(
                    series_title="show",
                    seasons=stats,
                    keep_last=keep_last,
                    keep_first_season=keep_first,
                    keep_specials=keep_specials,
                    flag_keep_conflicts=flag,
                    watchers_by_season=watchers,
                )
                checked += 1
                prunable, protected = set(plan.prunable), {p.season_number for p in plan.protected}
                assert not (prunable & protected)
                assert prunable | protected == set(numbers)
                if keep_specials:
                    assert 0 not in prunable
                if keep_first and real:
                    assert min(real) not in prunable
                if not flag:
                    assert plan.conflicts == []
                for conflict in plan.conflicts:
                    assert conflict.pruned_watchers > conflict.kept_watchers
                    assert conflict.kept_season != 0, "specials are not a meaningful comparison"
                    assert conflict.pruned_season != 0
        assert checked == len(SHOWS) * 32

    def test_raising_keep_last_never_grows_the_prunable_set(self) -> None:
        for show in SHOWS:
            stats = [_season(n) for n, _ in show["seasons"]]
            previous: set[int] | None = None
            for keep_last in (0, 1, 2, 3, 5, 10):
                plan = plan_series_prune(series_title="show", seasons=stats, keep_last=keep_last)
                current = set(plan.prunable)
                if previous is not None:
                    assert current <= previous
                previous = current

    def test_airing_and_incomplete_seasons_are_never_prunable(self) -> None:
        for show in SHOWS[:30]:
            numbers = [n for n, _ in show["seasons"]]
            if not numbers:
                continue
            target = numbers[-1]
            stats = [_season(n, wanted=12 if n == target else 0) for n in numbers]
            plan = plan_series_prune(
                series_title="show",
                seasons=stats,
                keep_last=0,
                keep_first_season=False,
                keep_specials=False,
                airing_seasons={target},
            )
            assert target not in plan.prunable

    def test_the_conflict_detector_never_compares_against_specials(self) -> None:
        """Regression: a kept-but-unwatched Season 0 must not flag every watched
        prunable season as 'Needs a look'."""
        plan = plan_series_prune(
            series_title="show",
            seasons=[_season(0), _season(1), _season(2), _season(3)],
            keep_last=1,
            keep_first_season=False,
            keep_specials=True,
            flag_keep_conflicts=True,
            watchers_by_season={0: 0, 1: 5, 2: 0, 3: 0},
        )
        assert all(c.kept_season != 0 for c in plan.conflicts)
        assert any(c.pruned_season == 1 for c in plan.conflicts), (
            "the real conflict (season 1 vs kept season 3) must still be flagged"
        )


class TestSequentialGuardPermutations:
    def test_binge_positions_hold_across_lookahead_and_toggle(self) -> None:
        shapes = [s for s in SHOWS if len([n for n, _ in s["seasons"] if n != 0]) >= 3][:40]
        assert shapes, "fixture must carry multi-season shows"
        for show in shapes:
            numbers = [n for n, _ in show["seasons"]]
            real = [n for n in numbers if n != 0]
            stats = [_season(n) for n in numbers]
            mid = real[len(real) // 2]
            finals = dict.fromkeys(real, 8)
            for lookahead in (0, 1, 3):
                for enabled in (True, False):
                    plan = plan_series_prune(
                        series_title="show",
                        seasons=stats,
                        keep_last=0,
                        keep_first_season=False,
                        progress_by_user={"viewer": {mid: 4}},
                        season_final_episode=finals,
                        season_lookahead=lookahead,
                        keep_in_progress=enabled,
                    )
                    protected = {p.season_number for p in plan.protected}
                    expected = {
                        mid + offset for offset in range(lookahead + 1) if mid + offset in numbers
                    }
                    if enabled:
                        assert expected <= protected
                    else:
                        assert not any(
                            p.reason == "a viewer is part-way through the show"
                            for p in plan.protected
                        )

    def test_an_unknown_final_episode_fails_closed_to_both_seasons(self) -> None:
        show = next(s for s in SHOWS if len([n for n, _ in s["seasons"] if n != 0]) >= 3)
        numbers = [n for n, _ in show["seasons"]]
        real = [n for n in numbers if n != 0]
        stats = [_season(n) for n in numbers]
        mid = real[len(real) // 2]
        plan = plan_series_prune(
            series_title="show",
            seasons=stats,
            keep_last=0,
            keep_first_season=False,
            progress_by_user={"viewer": {mid: 4}},
            season_final_episode={},
        )
        protected = {p.season_number for p in plan.protected}
        assert mid in protected
        if mid + 1 in numbers:
            assert mid + 1 in protected

    def test_hold_expiry_keeps_unknown_timestamps_and_zero_means_forever(self) -> None:
        from datetime import UTC, datetime, timedelta

        now = datetime(2026, 1, 1, tzinfo=UTC)
        progress = {"a": {3: 2}, "b": {5: 1}, "c": {2: None}}
        last = {
            "a": now - timedelta(days=60),
            "b": None,  # unreadable timestamp: the hold survives
            "c": now - timedelta(days=10),
        }
        assert set(active_progress(progress, last, now=now, hold_days=0)) == {"a", "b", "c"}
        assert set(active_progress(progress, last, now=now, hold_days=30)) == {"b", "c"}
        assert set(active_progress(progress, last, now=now, hold_days=180)) == {"a", "b", "c"}


# ---------------------------------------------------------------------------
# The policy hash: covers exactly the scoring semantics
# ---------------------------------------------------------------------------


class TestPolicyHash:
    def test_every_semantic_field_changes_the_hash_and_only_thresholds_spare_scoring(
        self,
    ) -> None:
        policy = DEFAULT_MOVIE_POLICY
        base_hash, base_scoring = policy.policy_hash(), policy.scoring_hash()
        post_score_fields = {"condemn_at", "coverage_floor_bp"}
        flips: dict[str, object] = {
            "condemn_at": policy.condemn_at % 100 + 1,
            "coverage_floor_bp": (policy.coverage_floor_bp + 1) % 10_000,
            "keep_last_seasons": policy.keep_last_seasons + 1,
            "keep_first_season": not policy.keep_first_season,
            "keep_last_scope": "requested",
            "season_lookahead": policy.season_lookahead + 1,
            "keep_in_progress": not policy.keep_in_progress,
            "in_progress_hold_days": policy.in_progress_hold_days + 1,
            "keep_specials": not policy.keep_specials,
            "flag_keep_conflicts": not policy.flag_keep_conflicts,
            "keep_tags": ["another-tag"],
            "keep_tags_match": "all",
            # A reallocation, not a bump: the total is pinned at 100, so the only weight
            # edit an operator can make is moving points between signals.
            "signals": balanced(
                [
                    {**s.model_dump(mode="json"), "weight": (s.weight + 7) % 101 or 1}
                    for s in policy.signals
                ]
            ),
        }
        for field_name, value in flips.items():
            changed = mutated(policy, **{field_name: value})
            assert changed.policy_hash() != base_hash, f"{field_name} not hashed"
            scoring_changed = changed.scoring_hash() != base_scoring
            assert scoring_changed == (field_name not in post_score_fields), (
                f"{field_name}: scoring hash coverage is wrong"
            )

    def test_the_hash_ignores_nothing_it_should_cover_on_a_round_trip(self) -> None:
        policy = DEFAULT_TV_POLICY
        again = PolicyBody.model_validate_json(policy.canonical_json())
        assert again.policy_hash() == policy.policy_hash()


# ---------------------------------------------------------------------------
# The validation <-> runtime contract: anything that validates must score
# ---------------------------------------------------------------------------


def _mutant_body(rng: random.Random) -> dict:
    """A near-valid policy body: the shipped defaults with a few random mutations, some
    legal and some not. Mirrors what an operator's UI edits actually produce."""
    body = rng.choice((DEFAULT_MOVIE_POLICY, DEFAULT_TV_POLICY)).model_dump(mode="json")
    for _ in range(rng.randint(0, 3)):
        roll = rng.random()
        if roll < 0.2 and body["gates"]:
            gate = rng.choice(body["gates"])
            gate[rng.choice(("threshold", "secondary", "window_days"))] = rng.choice(
                (-3, 0, 1, 75, 365, 1095, 10**6)
            )
            gate["enabled"] = rng.random() > 0.25
        elif roll < 0.4 and body["signals"]:
            signal = rng.choice(body["signals"])
            signal[rng.choice(("weight", "saturate_at", "floor"))] = rng.choice(
                (-1, 0, 1, 50, 100, 101, 1825)
            )
        elif roll < 0.55:
            body["custom_condemn"] = [
                {
                    "kind": rng.choice(("boolean", "graded")),
                    "name": rng.choice(("a", "unwatched", "x" * 61, "")),
                    "field": rng.choice([*BY_KEY, "bogus_field"]),
                    "op": rng.choice([o.value for o in Op]),
                    "value": rng.choice((True, False, 0, 365, "Genre01", "500", "A, B")),
                    "weight": rng.choice((0, 30, 100, 101, -1)),
                    "saturate_at": rng.choice((1, 100, 0)),
                    "floor": rng.choice((0, 50, 100)),
                }
            ]
        elif roll < 0.7:
            body["protect_conditions"] = [
                {
                    "field": rng.choice([*BY_KEY, "bogus_field"]),
                    "op": rng.choice([o.value for o in Op]),
                    "value": rng.choice((True, 5, "Genre01", "500", 10**13)),
                }
            ]
        elif roll < 0.85:
            body["graded_keeps"] = [
                {
                    "name": "keep",
                    "field": rng.choice([*BY_KEY, "bogus_field"]),
                    "max_discount": rng.choice((1, 40, 100, 0, 101)),
                    "floor": rng.choice((0, 10)),
                    "saturate_at": rng.choice((1, 20, 0)),
                    "direction": rng.choice(("high_keeps", "low_keeps", "bogus")),
                }
            ]
        else:
            body[rng.choice(("condemn_at", "coverage_floor_bp", "keep_last_seasons"))] = rng.choice(
                (-5, 0, 1, 50, 100, 101, 10000, 10001)
            )
    return body


class TestValidationRuntimeContract:
    def test_anything_that_validates_scores_and_inspects_without_an_exception(
        self,
    ) -> None:
        rng = random.Random(3)
        probe = MOVIES[:15] + SEASONS[:15]
        accepted = 0
        for _ in range(150):
            body = _mutant_body(rng)
            try:
                policy = PolicyBody.model_validate(body)
            except ValueError:
                continue
            accepted += 1
            gates = build_gates(policy)
            for v in probe:
                verdict, score, coverage_bp, _, _ = judge(v, policy, gates)
                assert verdict in ("protect", "abstain", "condemn")
                assert 0 <= score <= 100
                assert 0 <= coverage_bp <= 10000
            inspect(policy, ProfileSettings())
        assert accepted >= 20, "the mutation generator stopped producing valid policies"


# ---------------------------------------------------------------------------
# Property tests: the whole legal policy space, on real shapes
# ---------------------------------------------------------------------------


@st.composite
def legal_policies(draw: st.DrawFn) -> PolicyBody:
    media_type = draw(st.sampled_from(("movie", "tv")))
    base = DEFAULT_MOVIE_POLICY if media_type == "movie" else DEFAULT_TV_POLICY
    gates = []
    for g in base.gates:
        entry = g.model_dump(mode="json")
        entry["enabled"] = draw(st.booleans())
        if g.gate is GateId.RATING_FLOOR:
            entry["threshold"] = draw(st.integers(1, 100))
            entry["secondary"] = draw(st.integers(1, 3_000_000))
        elif g.gate is GateId.MIN_DORMANCY:
            entry["threshold"] = draw(st.integers(365, 10_000))
        elif g.gate is GateId.SERVER_POPULARITY:
            entry["threshold"] = draw(st.integers(1, 50))
        entry["window_days"] = draw(st.integers(1, 5000))
        gates.append(entry)
    signals = []
    for s in base.signals:
        saturate = draw(st.integers(1, 5000))
        signals.append(
            {
                "signal": s.signal.value,
                "weight": draw(st.integers(0, 100)),
                "saturate_at": saturate,
                "floor": draw(st.integers(0, saturate - 1)),
            }
        )
    signals = balanced(signals)
    return PolicyBody.model_validate(
        {
            **base.model_dump(mode="json"),
            "gates": gates,
            "signals": signals,
            "condemn_at": draw(st.integers(1, 100)),
            "coverage_floor_bp": draw(st.integers(0, 10_000)),
            "keep_last_seasons": draw(st.integers(0, 12)),
            "season_lookahead": draw(st.integers(0, 4)),
            "in_progress_hold_days": draw(st.integers(0, 1000)),
        }
    )


class TestPolicySpaceProperties:
    @settings(max_examples=80, deadline=None)
    @given(policy=legal_policies(), index=st.integers(0, len(VECTORS) - 1))
    def test_any_legal_policy_scores_any_real_shape_in_bounds(
        self, policy: PolicyBody, index: int
    ) -> None:
        vector = VECTORS[index]
        verdict, score, coverage_bp, evaluation, _ = judge(vector, policy)
        assert verdict in ("protect", "abstain", "condemn")
        assert 0 <= score <= 100
        assert 0 <= coverage_bp <= 10000
        if evaluation.protected and not vector.get("override"):
            assert verdict == "protect"

    @settings(max_examples=40, deadline=None)
    @given(policy=legal_policies(), index=st.integers(0, len(VECTORS) - 1))
    def test_full_degradation_never_condemns_under_any_legal_policy(
        self, policy: PolicyBody, index: int
    ) -> None:
        """The blackout case: every observable fact Unknown at once. Whatever the
        policy, the engine may keep or abstain; it may never condemn."""
        vector = VECTORS[index]
        if vector.get("override") == "reap":  # a hand-reap is the owner's own decision
            return
        blackout = degraded(vector, list(DEGRADABLE))
        verdict, score, _, _, _ = judge(blackout, policy)
        assert verdict != "condemn"
        assert score == 0
