# SPDX-License-Identifier: AGPL-3.0-or-later
"""The scoring surface, pinned to the ``SCORER_VERSION`` it was cut against.

An approved run is bound to its snapshot's ``policy_hash`` and the executor refuses to send
when the live hash no longer matches (rule 113). That hash digests the *policy body*, so an
upgrade the body cannot express is invisible to it: add a ``Facts`` field, a signal, or a
protection, and every stored body hashes exactly as before. Nothing marks the snapshot as
predating the build, and the plan already sitting on the Reap page executes on evidence the
old code gathered, uncovered by whatever the new code added.

The mechanism that closes that already exists and works. ``scorer_version`` is a
``PolicyBody`` field, ``policy_hash`` digests it with the rest of the body, and
``_pin_to_the_running_scorer`` rewrites a stored body's value to the running constant on
load, so bumping ``SCORER_VERSION`` moves every policy's hash and voids every pending
approval. What did not exist was anything making the author bump it. It was discipline, on
the change most likely to forget: the one that adds evidence rather than editing a threshold.

So this file records the surface, and the version it was recorded at, and fails when the two
disagree. Recorded as a literal list rather than a digest because the record is read by a
reviewer as much as by the suite: an added field shows up in the diff as one line beside a
``SCORER_VERSION`` that did or did not move, where a hex string shows a hex string.

**What a failure asks for is a decision, and bumping is not the only right answer.** The
worked example is the commit this file was written against. #492 added ``Facts.on_lists`` and
took ``whitelisted`` and ``curated_list`` out of the policy vocabulary, all with
``SCORER_VERSION`` sitting still -- which is this file's failure exactly. It was still
correct, because it invalidated through the body instead: both gates were rows in the shipped
default, so every stored body names them, ``convert_list_protections`` rewrites each one into
the equivalent ``on_list`` keep rule on load, and that edit moves ``policy_hash`` for every
install on its own. An operator whose decisions could change had their approval voided; one
whose body did not move had nothing reading the new fact. So the surface moved and the
meaning did not, and re-recording without a bump was right. What the gate buys is that
somebody had to work that out and write it down, rather than the question never being asked.

**What it does not catch.** Arithmetic. A ramp that changes shape, a weight table rebalanced,
a threshold that means something new -- the surface holds still through all of it and this
file stays green. Declarations are what a walk can see. ``test_policy_permutations``'s
``TestPinnedBaseline`` is the guard for that half: it replays de-identified fact shapes
through the shipped defaults and goes red when a verdict, score or coverage moves. It *asks*
for the bump in its failure text rather than enforcing one, because the fixture it compares
against is regenerated by the same change -- so between the two, a declaration that moves is
enforced and arithmetic that moves is announced.
"""

from __future__ import annotations

import dataclasses

from reaper.engine.gates import POLICY_AUTHORABLE_GATES, Facts, GateId
from reaper.engine.policy import SCORER_VERSION
from reaper.engine.signals import SignalId

#: The ``SCORER_VERSION`` the surface below was recorded against. Both move together or
#: neither does -- re-recording the list without touching this leaves every operator's
#: pending approval bound to a scorer that no longer exists.
_RECORDED_AT_SCORER_VERSION = 2

#: Every declaration a scan's numbers are drawn from, as ``_scoring_surface`` spells them.
_RECORDED_SURFACE: tuple[str, ...] = (
    "facts.days_observed_unwatched: Observation[float]",
    "facts.days_since_added: Observation[float]",
    "facts.distinct_watchers: Observation[int]",
    "facts.distinct_watchers_all_time: Observation[int]",
    "facts.genres: Observation[str]",
    "facts.history_reach_days: Observation[float]",
    "facts.imdb_rating_tenths: Observation[int]",
    "facts.imdb_votes: Observation[int]",
    "facts.in_curated_list: Observation[str]",
    "facts.is_managed: Observation[bool]",
    "facts.is_streaming_now: Observation[bool]",
    "facts.is_whitelisted: Observation[bool]",
    "facts.on_lists: Observation[str]",
    "facts.quality: Observation[str]",
    "facts.ratings: tuple[Rating, ...]",
    "facts.release_age_days: Observation[float]",
    "facts.requested: Observation[bool]",
    "facts.season_rank: Observation[int]",
    "facts.show_ended: Observation[bool]",
    "facts.size_bytes: Observation[int]",
    "facts.title: str",
    "gate.curated_list: not-authorable",
    "gate.custom: not-authorable",
    "gate.data_horizon: authorable",
    "gate.min_dormancy: authorable",
    "gate.others_watching: not-authorable",
    "gate.rating_floor: authorable",
    "gate.season_progression: not-authorable",
    "gate.server_popularity: authorable",
    "gate.streaming_now: authorable",
    "gate.unmanaged: not-authorable",
    "gate.whitelisted: not-authorable",
    "signal.few_watchers",
    "signal.low_rating",
    "signal.season_rank",
    "signal.size",
    "signal.unwatched",
)

_BUMP = (
    "The scoring surface moved, so decide what invalidates the plans approved under the old "
    "one. A scan under this code gathers or judges something the old one did not, and a "
    "stored policy body hashes the same either side of that -- so an approved run would "
    "execute on evidence gathered without it (rule 113). Two answers are legitimate and you "
    "have to pick one in writing. Either bump SCORER_VERSION in engine/policy.py, which "
    "moves every policy's hash and asks every operator to re-scan; or show that a loader "
    "shim already rewrites every affected stored body, which moves those hashes on its own "
    "(convert_list_protections is the worked example, see this file's docstring). Then set "
    "_RECORDED_AT_SCORER_VERSION to the running SCORER_VERSION and re-record the list above."
)


def _gate_role(gate: GateId) -> str:
    """Whether a policy body may still carry this gate, read off the one shipped declaration.

    Deliberately two answers and not four. A gate that stops being authorable leaves the
    operator's vocabulary, and *that* is what belongs on a surface record. Which mechanism
    took it -- retired outright, converted into a keep rule by a shim, emitted by the engine
    with no policy row -- is a question ``test_policy`` already owns and pins, and the only
    declaration in ``src`` that answers it is this set. An earlier draft guessed the rest and
    labeled the two gates #492 converted "engine-emitted", which was simply untrue.
    """
    return "authorable" if gate in POLICY_AUTHORABLE_GATES else "not-authorable"


def _scoring_surface(facts_cls: type = Facts) -> tuple[str, ...]:
    """Every evidence field, signal, and protection the running code declares.

    Derived from the declarations themselves rather than transcribed beside them, so the only
    hand-maintained copy is the recorded one this is compared against -- which is the copy a
    reviewer reads.

    A ``Facts`` field carries its annotation, not just its name: retyping one changes what the
    scan gathers as surely as adding one does (rules 140 and 142 are both that shape). The
    annotations are strings here because ``engine.gates`` imports ``annotations`` from
    ``__future__``, so this compares the declaration as written; a purely cosmetic re-spelling
    would fire it, and re-recording with no bump is the right answer to that one.

    ``facts_cls`` is a parameter so a test can hand it a stand-in for some future commit's
    ``Facts`` -- ``facts_codec._observation_fields`` takes one for the same reason.
    """
    lines = [f"facts.{field.name}: {field.type}" for field in dataclasses.fields(facts_cls)]
    lines += [f"signal.{signal.value}" for signal in SignalId]
    lines += [f"gate.{gate.value}: {_gate_role(gate)}" for gate in GateId]
    return tuple(sorted(lines))


class TestTheSurfaceAndTheScorerVersionMoveTogether:
    def test_the_recorded_surface_is_the_one_the_code_declares(self) -> None:
        """The gate. It fails on the commit that adds the field, not on the server that
        deletes under it."""
        assert _scoring_surface() == _RECORDED_SURFACE, _BUMP

    def test_the_record_names_the_running_scorer(self) -> None:
        """The other half. Re-recording the surface while leaving this behind would swallow
        the failure above and leave every pending approval bound to the superseded scorer,
        which is the bug this file exists for."""
        assert _RECORDED_AT_SCORER_VERSION == SCORER_VERSION, _BUMP


class TestTheWalkSeesWhatItClaimsTo:
    """Rule 118: a matching record proves nothing about a walk that stopped collecting, so
    the two assumptions the record was cut under get their own tests."""

    def test_a_facts_field_this_commit_has_never_seen_reaches_the_surface(self) -> None:
        """Rule 145: the walk is proven against a member it did not collect, not only against
        the ones already in the record. A stand-in stands for the commit that adds the field,
        which is the commit this whole file is for."""
        added = "surface_walk_probe"
        assert added not in {f.name for f in dataclasses.fields(Facts)}, (
            f"{added} is a real field now; the stand-in needs a name Facts does not carry, or "
            "make_dataclass raises on the duplicate and this reads as a walk that broke"
        )
        future_facts = dataclasses.make_dataclass(
            "Facts",
            [
                *(
                    (f.name, f.type, dataclasses.field(default=None))
                    for f in dataclasses.fields(Facts)
                ),
                (added, "Observation[int]", dataclasses.field(default=None)),
            ],
            frozen=True,
        )

        surface = _scoring_surface(future_facts)

        assert f"facts.{added}: Observation[int]" in surface
        assert surface != _RECORDED_SURFACE

    def test_a_facts_annotation_is_the_string_the_record_was_cut_from(self) -> None:
        """``field.type`` is source text under ``from __future__ import annotations`` and the
        type object without it. The surface renders either through an f-string, so dropping
        that import from ``engine.gates`` would silently re-spell all twenty lines as
        ``reaper.engine.observation.Observation[int]`` and the gate would fire for a reason
        nobody could read off the failure."""
        annotation = {f.name: f.type for f in dataclasses.fields(Facts)}["size_bytes"]

        assert isinstance(annotation, str)
        assert annotation == "Observation[int]"
