"""baseline schema

The whole schema, in one revision.

**Until Reaper's first release this migration is rewritten in place**, not appended
to: nobody is running the tool yet, so there is no data to preserve and no upgrade
path to honour. A chain of migrations between schemas that never shipped is pure cost
-- it slows every fresh ``alembic upgrade head`` and each link is somewhere a SQLite
batch-mode bug can hide. To change the schema: edit the models, delete ``reaper.db``,
delete this file, regenerate, and upgrade from empty.

**Once a version is tagged, this stops.** From then on the baseline is frozen and every
schema change is its own additive revision, because someone out there has data.

Note what is *not* here: the cache tables (``imdb_rating``, ``watch_event``, ...). They
live in ``cache.db``, are created by raw DDL, and are never migrated -- they are
rebuildable by definition. ``alembic/env.py`` filters them out of autogenerate, and a
test asserts no migration ever creates one.

Revision ID: 22777b2b5015
Revises:
Create Date: 2026-07-14 18:40:20.622099
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '22777b2b5015'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_setting',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value_json', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_app_setting'))
    )
    op.create_table('app_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.Enum('PLEX', 'LOCAL', name='authprovider', native_enum=False), nullable=False),
    sa.Column('plex_account_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('thumb_url', sa.String(length=500), nullable=True),
    sa.Column('password_hash', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('last_login_at', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_app_user')),
    sa.UniqueConstraint('plex_account_id', name=op.f('uq_app_user_plex_account_id')),
    sa.UniqueConstraint('username', name=op.f('uq_app_user_username'))
    )
    op.create_table('first_flagged',
    sa.Column('media_key', sa.String(length=100), nullable=False),
    sa.Column('first_flagged_at', sa.Integer(), nullable=False),
    sa.Column('last_seen_condemned_at', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('media_key', name=op.f('pk_first_flagged'))
    )
    op.create_table('instance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('SONARR', 'RADARR', 'TAUTULLI', 'SEERR', name='instancekind', native_enum=False), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('base_url', sa.String(length=500), nullable=False),
    sa.Column('api_key_enc', sa.Text(), nullable=False),
    sa.Column('api_path_prefix', sa.String(length=20), nullable=False),
    sa.Column('detected_version', sa.String(length=50), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('verify_tls', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('last_ok_at', sa.Integer(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_instance')),
    sa.UniqueConstraint('kind', 'name', name=op.f('uq_instance_kind'))
    )
    op.create_table('pending_plex_login',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pin_id', sa.Integer(), nullable=False),
    sa.Column('pin_code', sa.String(length=20), nullable=False),
    sa.Column('purpose', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pending_plex_login'))
    )
    with op.batch_alter_table('pending_plex_login', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pending_plex_login_pin_id'), ['pin_id'], unique=True)

    op.create_table('plex_server',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('machine_identifier', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('connection_uri', sa.String(length=500), nullable=False),
    sa.Column('connections_json', sa.Text(), nullable=False),
    sa.Column('token_enc', sa.Text(), nullable=False),
    sa.Column('owner_plex_account_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('last_ok_at', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plex_server')),
    sa.UniqueConstraint('machine_identifier', name=op.f('uq_plex_server_machine_identifier'))
    )
    op.create_table('policy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('policy_hash', sa.String(length=64), nullable=False),
    sa.Column('body_json', sa.Text(), nullable=False),
    sa.Column('media_type', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_policy'))
    )
    with op.batch_alter_table('policy', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_policy_policy_hash'), ['policy_hash'], unique=True)

    op.create_table('recovery_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.Integer(), nullable=False),
    sa.Column('used_at', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recovery_token'))
    )
    with op.batch_alter_table('recovery_token', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recovery_token_token_hash'), ['token_hash'], unique=True)

    op.create_table('snapshot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('policy_hash', sa.String(length=64), nullable=False),
    sa.Column('scoring_hash', sa.String(length=64), nullable=False),
    sa.Column('horizon_at', sa.Integer(), nullable=False),
    sa.Column('item_count', sa.Integer(), nullable=False),
    sa.Column('degraded', sa.Boolean(), nullable=False),
    sa.Column('degraded_reason', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_snapshot'))
    )
    with op.batch_alter_table('snapshot', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_snapshot_policy_hash'), ['policy_hash'], unique=False)

    op.create_table('auth_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.Integer(), nullable=False),
    sa.Column('last_seen_at', sa.Integer(), nullable=True),
    sa.Column('user_agent', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], name=op.f('fk_auth_session_user_id_app_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_auth_session'))
    )
    with op.batch_alter_table('auth_session', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auth_session_token_hash'), ['token_hash'], unique=True)

    op.create_table('candidate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snapshot_id', sa.Integer(), nullable=False),
    sa.Column('media_key', sa.String(length=100), nullable=False),
    sa.Column('plex_rating_key', sa.Integer(), nullable=True),
    sa.Column('poster_rating_key', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('media_type', sa.String(length=10), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('poster_url', sa.String(length=1000), nullable=True),
    sa.Column('requested_by', sa.String(length=200), nullable=True),
    sa.Column('genres_json', sa.Text(), nullable=True),
    sa.Column('quality', sa.String(length=100), nullable=True),
    sa.Column('tmdb_id', sa.Integer(), nullable=True),
    sa.Column('imdb_id', sa.String(length=20), nullable=True),
    sa.Column('title_slug', sa.String(length=200), nullable=True),
    sa.Column('video_resolution', sa.String(length=10), nullable=True),
    sa.Column('content_rating', sa.String(length=20), nullable=True),
    sa.Column('runtime_minutes', sa.Integer(), nullable=True),
    sa.Column('ratings_json', sa.Text(), nullable=True),
    sa.Column('group_key', sa.String(length=100), nullable=True),
    sa.Column('group_title', sa.String(length=500), nullable=True),
    sa.Column('verdict', sa.String(length=10), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('coverage_bp', sa.Integer(), nullable=False),
    sa.Column('explanation_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['snapshot_id'], ['snapshot.id'], name=op.f('fk_candidate_snapshot_id_snapshot'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_candidate')),
    sa.UniqueConstraint('snapshot_id', 'media_key', name=op.f('uq_candidate_snapshot_id'))
    )
    with op.batch_alter_table('candidate', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_candidate_media_key'), ['media_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_candidate_group_key'), ['group_key'], unique=False)

    op.create_table('profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('active_policy_id', sa.Integer(), nullable=False),
    sa.Column('settings_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['active_policy_id'], ['policy.id'], name=op.f('fk_profile_active_policy_id_policy')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_profile')),
    sa.UniqueConstraint('name', name=op.f('uq_profile_name'))
    )
    op.create_table('reap_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snapshot_id', sa.Integer(), nullable=False),
    sa.Column('policy_hash', sa.String(length=64), nullable=False),
    sa.Column('state', sa.Enum('PLANNED', 'EXECUTING', 'COMPLETED', 'ABORTED', name='runstate'), nullable=False),
    sa.Column('approved_manifest_hash', sa.String(length=64), nullable=False),
    sa.Column('approved_by', sa.String(length=100), nullable=False),
    sa.Column('approved_at', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.Integer(), nullable=True),
    sa.Column('finished_at', sa.Integer(), nullable=True),
    sa.Column('aborted_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['snapshot_id'], ['snapshot.id'], name=op.f('fk_reap_run_snapshot_id_snapshot'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reap_run'))
    )
    with op.batch_alter_table('reap_run', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reap_run_policy_hash'), ['policy_hash'], unique=False)

    op.create_table('action_step',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('media_key', sa.String(length=100), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('path', sa.String(length=500), nullable=False),
    sa.Column('body_json', sa.Text(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=64), nullable=False),
    sa.Column('state', sa.Enum('PENDING', 'SENT', 'VERIFIED', 'FAILED', 'SKIPPED', name='stepstate'), nullable=False),
    sa.Column('verification_json', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('sent_at', sa.Integer(), nullable=True),
    sa.Column('verified_at', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['reap_run.id'], name=op.f('fk_action_step_run_id_reap_run'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_action_step'))
    )
    with op.batch_alter_table('action_step', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_action_step_idempotency_key'), ['idempotency_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_action_step_media_key'), ['media_key'], unique=False)

    op.create_table('autonomy_grant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('policy_hash', sa.String(length=64), nullable=False),
    sa.Column('backtest_passed', sa.Boolean(), nullable=False),
    sa.Column('clean_supervised_runs', sa.Integer(), nullable=False),
    sa.Column('granted_at', sa.Integer(), nullable=False),
    sa.Column('granted_by', sa.String(length=100), nullable=False),
    sa.CheckConstraint('backtest_passed = 1', name=op.f('ck_autonomy_grant_backtest_required')),
    sa.CheckConstraint('clean_supervised_runs >= 3', name=op.f('ck_autonomy_grant_min_supervised_runs')),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], name=op.f('fk_autonomy_grant_profile_id_profile'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_autonomy_grant')),
    sa.UniqueConstraint('profile_id', 'policy_hash', name=op.f('uq_autonomy_grant_profile_id'))
    )
    with op.batch_alter_table('autonomy_grant', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_autonomy_grant_policy_hash'), ['policy_hash'], unique=False)

    op.create_table('whitelist',
    sa.Column('media_key', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('decision', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('media_key', name=op.f('pk_whitelist'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('whitelist')
    with op.batch_alter_table('autonomy_grant', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_autonomy_grant_policy_hash'))

    op.drop_table('autonomy_grant')
    with op.batch_alter_table('action_step', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_action_step_media_key'))
        batch_op.drop_index(batch_op.f('ix_action_step_idempotency_key'))

    op.drop_table('action_step')
    with op.batch_alter_table('reap_run', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reap_run_policy_hash'))

    op.drop_table('reap_run')
    op.drop_table('profile')
    with op.batch_alter_table('candidate', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_candidate_group_key'))
        batch_op.drop_index(batch_op.f('ix_candidate_media_key'))

    op.drop_table('candidate')
    with op.batch_alter_table('auth_session', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auth_session_token_hash'))

    op.drop_table('auth_session')
    with op.batch_alter_table('snapshot', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_snapshot_policy_hash'))

    op.drop_table('snapshot')
    with op.batch_alter_table('recovery_token', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recovery_token_token_hash'))

    op.drop_table('recovery_token')
    with op.batch_alter_table('policy', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_policy_policy_hash'))

    op.drop_table('policy')
    op.drop_table('plex_server')
    with op.batch_alter_table('pending_plex_login', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pending_plex_login_pin_id'))

    op.drop_table('pending_plex_login')
    op.drop_table('instance')
    op.drop_table('first_flagged')
    op.drop_table('app_user')
    op.drop_table('app_setting')
    # ### end Alembic commands ###
