// SPDX-License-Identifier: AGPL-3.0-or-later
//
// One autogenerated sidebar over the whole manual.
//
// Autogenerated rather than hand-listed on purpose: a hand-listed sidebar is a second copy of the
// page list, and half these pages are written by a generator, so the copy would go stale exactly
// when a doc is added and nobody thinks to edit this file. Order comes from each page's
// `sidebar_position` (the generator writes one from the doc's place in the app's own index) and
// each directory's `_category_.json`.

import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  manual: [{ type: "autogenerated", dirName: "." }],
};

export default sidebars;
